#pragma once

enum system_call_numbers {
    SYSCALL_YIELD,
    SYSCALL_TERMINATE,
    SYSCALL_MAPVIRT,
    SYSCALL_UNMAPVIRT,
    SYSCALL_OPEN,
    SYSCALL_READWRITE,
    SYSCALL_CLOSE,
    SYSCALL_SEEK,
    SYSCALL_DUP,
    SYSCALL_EXIT,
    SYSCALL_REMOVE,
    SYSCALL_MPROTECT,
    SYSCALL_PREPEXEC,
    
    _SYSCALL_NUM_ENTRIES
};

