#pragma once

enum system_call_numbers {
    SYSCALL_YIELD,
    SYSCALL_TERMINATE,
    SYSCALL_MAPVIRT,
    SYSCALL_UNMAPVIRT,
    SYSCALL_OPEN,
    SYSCALL_READWRITE,
    SYSCALL_CLOSE,
    SYSCALL_SEEK,
    SYSCALL_DUP,
    SYSCALL_EXIT,
    SYSCALL_REMOVE,
    SYSCALL_MPROTECT,
    SYSCALL_PREPEXEC,
    SYSCALL_WAITPID,
    SYSCALL_FORK,
    SYSCALL_GETPID,
    SYSCALL_GETTID,
    SYSCALL_IOCTL,
    SYSCALL_STAT,
    SYSCALL_CHDIR,
    SYSCALL_INFO,
    SYSCALL_TIME,
    SYSCALL_NANOSLEEP,
    SYSCALL_SIGNAL,
    SYSCALL_PGID,
    SYSCALL_ALARM,
    
    _SYSCALL_NUM_ENTRIES
};

